name: cs529_proj1
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numba
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - mlflow
  - pre-commit
  - ipython
  - networkx
  - graphviz
  - python-graphviz
  - pydot
